### ISSUE TITLE
[体验反馈] post提交之后所有格式丢失

### ISSUE THREAD

**Issue by DCTewi** [actips/actips-front#4]
### 问题  

编辑状态的字体,缩进和链接之类的格式,在提交之后将会全部丢失.  

### 说明

**编辑状态**  

[![2019-04-28 21-56-28 的屏幕截图.png](https://i.loli.net/2019/04/28/5cc5b1e554f05.png)](https://i.loli.net/2019/04/28/5cc5b1e554f05.png)  

**显示效果**  

[![2019-04-28 21-56-46 的屏幕截图.png](https://i.loli.net/2019/04/28/5cc5b1e58c2db.png)](https://i.loli.net/2019/04/28/5cc5b1e58c2db.png)

但是再次编辑的时候格式还在,是不是只是显示问题?

**Comment by DCTewi** [comment]
似乎标签里的格式还在,是不是css加载问题?

**Comment by fish-ball** [comment]
这里的话，现在会吃掉样式，代码建议在 Code 块里面填，这样可以高亮显示。

其他的内容，本质上没有存在“格式”的需要，但是对于没有指定格式的内容前端排版可能还没有做得很好。

后续开发也会开发 Markdown 模式，使用 Mardown 进行编辑（可选或者强制使用，到时再做个取舍），到时用 Markdown撰写就不会有这种顾虑了。

**Comment by DCTewi** [comment]
之前没看到code块，已经修改啦。

滋滋markdown！
